### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by tkvw** [interactivethings/catalog#305]
Whenever I run a `catalog build` on my windows environment (windows 10, npm 5.3.0, node@v8.1.4)
I get the following error: 
```
catalog\node_modules\args\lib\utils.js:298
      throw err;
      ^

Error: spawn catalog.js-build ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.
```

Is this a windows specific error?

**Comment by herrstucki** [comment]
Looks like a bug in leo/args, see https://github.com/leo/args/issues/88

**Comment by ntwcklng** [comment]
@herrstucki fixed in `args 3.0.5` ✌️

**Comment by herrstucki** [comment]
Thanks @ntwcklng! 🙏 

@tkvw can you confirm that this is fixed now? I don't think Catalog itself needs to bump its version but you may need to re-create your npm/yarn lockfile, so the new version of args gets installed.

**Comment by tkvw** [comment]
Yes, it works now. Thanks guys! 👍
